// Entirely synthesized local audio: no downloads, licensed samples or network.
export class GameAudio {
  constructor(){this.ctx=null;this.muted=false;this.lastStep=0;}
  init(){if(!this.ctx){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;this.ctx=new Audio();this.master=this.ctx.createGain();this.master.gain.value=this.muted?0:.45;this.master.connect(this.ctx.destination);const size=this.ctx.sampleRate;this.noise=this.ctx.createBuffer(1,size,this.ctx.sampleRate);const data=this.noise.getChannelData(0);for(let i=0;i<size;i++)data[i]=Math.random()*2-1;}this.ctx.resume().catch(()=>{});}
  mute(value){this.muted=value;if(this.master)this.master.gain.setTargetAtTime(value?0:.45,this.ctx.currentTime,.04);}
  tone(f,end,duration,volume=.2,type='sine',delay=0){if(!this.ctx||this.muted)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(10,end),t+duration);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(volume,t+.005);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
  hiss(duration,volume,freq=1000,delay=0){if(!this.ctx||this.muted)return;const t=this.ctx.currentTime+delay,s=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=this.noise;filter.type='lowpass';filter.frequency.value=freq;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);s.connect(filter);filter.connect(g);g.connect(this.master);s.start(t,Math.random()*.5);s.stop(t+duration);s.onended=()=>{s.disconnect();filter.disconnect();g.disconnect();};}
  play(name,amount=1){if(!this.ctx)return;switch(name){case'explosion':this.hiss(.55,.85,900);this.tone(75,22,.55,.85,'triangle');this.hiss(.2,.35,2600);break;case'yeet':this.hiss(.25,.28,1800);this.tone(120,650,.25,.18,'triangle');break;case'spitWarning':this.tone(550,850,.55,.13,'sawtooth');break;case'pistol':this.hiss(.13,.7,4200);this.tone(180,45,.16,.55,'triangle');this.tone(1000,220,.06,.13,'square');break;case'shotgun':this.hiss(.32,1,2600);this.tone(95,25,.35,.9,'triangle');this.hiss(.1,.16,1800,.35);break;case'hit':this.hiss(.065,.18,1800);this.tone(180,80,.08,.2);break;case'head':this.tone(1700,800,.11,.16,'triangle');break;case'kill':this.tone(460,620,.13,.10,'sine');break;case'reload':this.hiss(.07,.2,3800);this.tone(320,180,.09,.12,'square',.15);break;case'ready':this.hiss(.06,.2,3000);break;case'empty':this.tone(170,120,.05,.12,'square');break;case'hurt':this.hiss(.19,.22,600);this.tone(70,38,.2,.35);break;case'pickup':for(let i=0;i<3;i++)this.tone(480+i*180,500+i*180,.15,.12,'sine',i*.075);break;case'wave':this.tone(160,80,.9,.25,'sawtooth');this.tone(240,120,.8,.08,'triangle',.15);break;case'clear':for(let i=0;i<4;i++)this.tone([330,440,550,660][i],[330,440,550,660][i],.3,.13,'triangle',i*.11);break;case'foot':this.hiss(.07,.055*amount,450);break;case'growl':this.tone(80+Math.random()*25,40,.55,.1*amount,'sawtooth');break;}}
}
