import test from 'node:test';
import assert from 'node:assert/strict';
import {createNavigation} from '../src/game/navigation.js';
import {enemyType,enemyStats,waveConfig,explosionDamage,scoreMultiplier} from '../src/game/encounters.js';
import {createYeet,chargeAt,launchVelocity,selectYeetTarget} from '../src/game/yeet.js';
test('Hordes escalate, sprinters outrun walking, and specials have distinct introductions',()=>{
 for(let wave=1;wave<=10;wave++){const cfg=waveConfig(wave);assert(cfg.count>=24&&cfg.maxAlive<=52);if(wave>1)assert(cfg.count>waveConfig(wave-1).count);assert(enemyStats('runner',wave).speed>4.2);assert(enemyStats('runner',wave).speed<7.4);const types=new Set(Array.from({length:100},(_,i)=>enemyType(wave,()=>i/100)));assert(types.has('runner'));assert.equal(types.has('spitter'),wave>=2);assert.equal(types.has('brute'),wave>=3);assert(types.has('walker'));}
});
test('Explosions fall off and stop at the radius; streak bonuses are capped',()=>{assert(explosionDamage(1,7,220)>explosionDamage(5,7,220));assert.equal(explosionDamage(7,7,220),0);assert.equal(explosionDamage(9,7,220),0);assert.equal(scoreMultiplier(5),2);assert.equal(scoreMultiplier(500),8);});
test('Placed barricades block movement and update flow routes; removal restores the corridor',()=>{const nav=createNavigation({obstacles:[],walkBoundsAt:()=>({minX:-5,maxX:5})},{minX:-5,maxX:5,minZ:0,maxZ:30});nav.setDynamic([-1,-.5,0,.5,1].map(x=>({x,z:15,r:.3})));nav.update(0,22);assert(!nav.lineClear(0,10,0,22));const p={x:0,z:10};for(let i=0;i<900;i++){const d=nav.direction(p.x,p.z,0,22),n=Math.hypot(d.x,d.z);if(n<.1)break;nav.move(p,d.x/n*.04,d.z/n*.04);}assert(Math.hypot(p.x,p.z-22)<.8);nav.setDynamic([]);nav.update(0,22);assert(nav.lineClear(0,10,0,22));});
const target=(x,z,type='walker')=>({x,z,type,health:60,warning:0,stagger:0});
function setup(enemies=[target(0,-2)],extra={}){let dominoes=0;const sounds=[];const player={x:0,z:0};const y=createYeet({player:()=>player,enemies:()=>enemies,direction:()=>({x:0,y:-.1,z:-1}),visible:()=>true,clear:()=>true,floor:()=>0,toast:()=>{},sound:n=>sounds.push(n),damage:(e,d)=>{e.health-=d;if(e.health<=0)enemies.splice(enemies.indexOf(e),1);},domino:()=>dominoes++,pose:()=>{},...extra});return{y,enemies,player,sounds,get dominoes(){return dominoes;}};}
test('Yeet pulse rewards timing and aim angle controls the actual launch',()=>{assert.equal(chargeAt(0),.45);assert.equal(chargeAt(.5),1);assert.equal(chargeAt(1),.45);assert(launchVelocity({x:0,y:0,z:-1},0).z<-14,'a tap already throws hard');assert(launchVelocity({x:0,y:1,z:-1},1).y>launchVelocity({x:0,y:0,z:-1},1).y);assert(launchVelocity({x:0,y:0,z:-1},1).z<launchVelocity({x:0,y:0,z:-1},.1).z);});
test('Yeet lock excludes hidden, distant, emerging and behind-player enemies',()=>{const front=target(0,-3),list=[target(0,1),target(0,-8),{...target(0,-1),warning:1},front];assert.equal(selectYeetTarget(list,{x:0,z:0},{x:0,z:-1},()=>true),front);assert.equal(selectYeetTarget(list,{x:0,z:0},{x:0,z:-1},()=>false),null);});
test('Flying zombie hits a crowd once each even at coarse frame intervals',()=>{const a=setup([target(0,-2),target(0,-3),target(0,-4)]);a.y.begin();a.y.update(.62);a.y.release();assert.equal(a.y.flights.length,1);for(let i=0;i<80;i++)a.y.update(.05);assert.equal(a.dominoes,2);assert.equal(a.enemies.length,0);assert.equal(a.y.flights.length,0);});
test('Yeet cancels cleanly and refuses a target that escaped while charging',()=>{const a=setup();a.y.begin();a.y.cancel();a.y.release();assert.equal(a.y.flights.length,0);a.y.begin();a.enemies[0].z=-12;a.y.release();assert.equal(a.y.flights.length,0);assert.equal(a.y.cooldown,0);});
test('Brutes stagger instead of launching and cooldown prevents immediate repeated yeets',()=>{const a=setup([{...target(0,-2,'brute'),health:280}]);a.y.begin();a.y.release();assert.equal(a.y.flights.length,0);assert(a.enemies[0].stagger>=1);assert(a.enemies[0].health<280);a.y.begin();assert.equal(a.y.held,false);a.y.update(3);a.y.begin();assert.equal(a.y.held,true);});
test('Yeet impacts scenery without escaping the street',()=>{const a=setup(undefined,{clear:(x,z)=>z>-5});a.y.begin();a.y.release();for(let i=0;i<60;i++)a.y.update(1/60);assert.equal(a.enemies.length,0);assert.equal(a.y.flights.length,0);});
