import test from 'node:test';
import assert from 'node:assert/strict';
import {RUNNER,RUNNER_HAZARDS,createRunner,runnerAction,updateRunner,runnerReward} from '../src/game/runner.js';
function empty(){const s=createRunner(()=>.5);Object.assign(s,{active:true,nextRow:10000,nextCoin:10000});return s;}
function tick(s,seconds){for(let i=0;i<seconds*120;i++)updateRunner(s,1/120);}
function hazard(type,distance,lane=1){return{id:1,type,lane,x:RUNNER.lanes[lane],distance,...RUNNER_HAZARDS[type]};}
test('Runner lane changes are fast but continuous, and clamp to three lanes',()=>{const s=empty();runnerAction(s,'right');tick(s,.08);assert(s.x>0&&s.x<2.1);tick(s,.1);assert.equal(s.x,2.1);runnerAction(s,'right');assert.equal(s.lane,2);runnerAction(s,'left');runnerAction(s,'left');runnerAction(s,'left');tick(s,.4);assert.equal(s.lane,0);assert.equal(s.x,-2.1);});
test('Original jump height clears boxes; standing collides',()=>{const a=empty(),b=empty();a.rows=[hazard('boxes',5)];b.rows=[hazard('boxes',5)];runnerAction(a,'up');tick(a,.33);assert(a.y>1.3);tick(a,.22);tick(b,.55);assert.equal(a.lives,2);assert.equal(b.lives,1);});
test('Sliding clears low banners, but jumping or standing does not',()=>{for(const action of ['down',null,'up']){const s=empty();s.rows=[hazard('banner',4)];if(action)runnerAction(s,action);tick(s,.45);assert.equal(s.lives,action==='down'?2:1);}});
test('Down during a jump fast-falls and lands promptly',()=>{const s=empty();runnerAction(s,'up');tick(s,.25);assert(s.y>1);runnerAction(s,'down');tick(s,.12);assert.equal(s.y,0);assert(s.slide>0);});
test('Two collisions end a run, with a grace period preventing repeated hits',()=>{const s=empty();s.rows=[hazard('zombie',2),{...hazard('phone',3),id:2},{...hazard('cafe',42),id:3}];tick(s,.6);assert.equal(s.lives,1);tick(s,4);assert.equal(s.lives,0);assert(s.over&&!s.active);const d=s.distance;tick(s,1);assert.equal(s.distance,d);});
test('Creemee grants source flight duration and collects across lanes; magnet lasts seven seconds',()=>{const s=empty();s.collectibles=[{id:1,kind:'creemee',x:0,lane:1,y:1,distance:1}];tick(s,.1);assert(s.flight>4.3&&s.flight<=4.5);s.collectibles.push({id:2,kind:'coin',x:-2.1,lane:0,y:.9,distance:s.distance+3});tick(s,.1);assert.equal(s.coins,1);s.flight=0;s.y=0;s.collectibles=[{id:3,kind:'magnet',x:0,lane:1,y:1,distance:s.distance+1}];tick(s,.1);assert(s.magnet>6.8&&s.magnet<=7);});
test('Portal lap wraps the updated street while distance and score continue',()=>{const s=empty();s.distance=459.5;tick(s,.1);assert.equal(s.lap,1);assert(s.z>478&&s.z<480);assert(s.events.some(e=>e.type==='lap'));assert(s.distance>460);});
test('Generated rows always leave a lane open and avoid the portal landing buffer',()=>{let seed=7;const s=createRunner(()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;});s.active=true;s.invulnerable=1000;const seen=new Map();for(let i=0;i<2000;i++){updateRunner(s,.05);for(const o of s.rows){const key=o.distance;if(!seen.has(key))seen.set(key,new Set());seen.get(key).add(o.lane);assert(o.distance%460>=18&&o.distance%460<=445);}}assert(seen.size>80);for(const lanes of seen.values())assert(lanes.size<3);assert(s.speed<=24);});
test('Runner rewards are bounded and do not mutate the result',()=>{const s=empty();s.coins=999;s.score=999999;assert.deepEqual(runnerReward(s),{score:1000,pistol:60,shotgun:12,health:25});assert.equal(s.coins,999);});
