import test from 'node:test';
import assert from 'node:assert/strict';
import {createSkater,updateSkater,popSkater} from '../src/game/skate.js';
import {createCourseData} from '../src/game/skate-course-data.js';
const course=createCourseData(),nav={move(p,x,z){p.x+=x;p.z+=z;}},neutral={forward:0,steer:0,look:0,charge:false},flat={rails:[],support:()=>({height:0,kind:'street',feature:null})};
function run(s,seconds,input=neutral,c=course){let highest=s.y;for(let i=0;i<seconds*120;i++){updateSkater(s,1/120,input,nav,()=>0,c);highest=Math.max(highest,s.y);}return highest;}
test('Air spin preserves horizontal travel instead of turning the flight path',()=>{const s=createSkater();Object.assign(s,{active:true,speed:9});popSkater(s);const v=s.vz;run(s,.4,{...neutral,steer:1},flat);assert(s.yaw<-1.5);assert(Math.abs(s.x)<.001);assert.equal(s.vz,v);assert(s.z<-3);});
test('Halfpipe launches above coping and returns the rider into its transition',()=>{const b=course.halfpipes[0],s=createSkater();Object.assign(s,{active:true,x:b.x,z:b.z,speed:11.5});const highest=run(s,6);assert(highest>b.height+1);assert(s.events.some(e=>e.type==='land'&&e.name.includes('halfpipe')));assert(Math.abs(s.z-b.z)<b.length/2);assert(!s.events.some(e=>e.type==='bail'));});
test('Large bank carries momentum into a transfer and lands cleanly',()=>{const b=course.banks[0],s=createSkater();Object.assign(s,{active:true,x:b.x,z:b.z+7,speed:10});const high=run(s,3);assert(high>b.height+.7);assert(s.events.some(e=>e.type==='land'&&e.name.includes('transfer')));assert(s.speed>8);});
test('Ground approach cannot teleport onto the vertical side of a halfpipe',()=>{const b=course.halfpipes[0],s=createSkater();Object.assign(s,{active:true,x:b.x,z:b.z+b.length/2+1,speed:6});run(s,1);assert(s.z>=b.z+b.length/2);assert(s.y<.1);});
test('Grind pop banks its rail time into the next landing',()=>{const s=createSkater(),rail={x:0,z0:-10,z1:10,height:.66,name:'Test rail'};Object.assign(s,{active:true,x:0,z:0,y:.66,speed:6,vx:0,vz:-6,state:'grind',grind:{rail,dir:-1},grindTime:1});popSkater(s,'kickflip');run(s,2,neutral,flat);const landing=s.events.find(e=>e.type==='land');assert(landing.name.includes('50–50')&&landing.name.includes('Kickflip'));assert(landing.points>400);});
test('Releasing steering before touchdown assists a nearly complete 180',()=>{const s=createSkater();Object.assign(s,{active:true,speed:7,charge:.45});popSkater(s);run(s,.56,{...neutral,steer:1},flat);run(s,1,neutral,flat);assert.equal(s.state,'ride');assert(s.events.some(e=>e.type==='land'&&e.name.includes('180')));assert(s.speed<0);});
test('Halfpipe transitions launch higher than the coping with room to spin',()=>{const b=course.halfpipes[0],s=createSkater();Object.assign(s,{active:true,x:b.x,z:b.z,speed:13});const highest=run(s,6);assert(highest>b.height+2.5,String(highest));assert(!s.events.some(e=>e.type==='bail'));});
test('Tap ollie at street speed hops onto a low rail and the magnet corrects a sideways approach',()=>{const rail=course.rails.find(r=>r.name==='Pharmacy rail'),s=createSkater();Object.assign(s,{active:true,x:rail.x+.9,z:rail.z0+2.5,speed:8,vx:0,vz:-8});s.charge=.06;popSkater(s);assert(s.vy<6.5,'a quick tap stays a small hop: '+s.vy);run(s,1.2,neutral,{...course,support:()=>({height:0,kind:'street',feature:null})});assert(s.events.some(e=>e.type==='grindStart'&&e.name==='Pharmacy rail'),JSON.stringify(s.events));});
test('Street benches are rideable rails and the new rails are clear of the transitions',()=>{const benches=course.rails.filter(r=>r.bench);assert.equal(benches.length,11);for(const b of benches)assert(b.height>.4&&b.height<.6&&b.z1-b.z0<2.2);assert(course.rails.length>=22);for(const r of course.rails)for(const f of course.features)assert(Math.abs(r.x-f.x)>f.width/2+.3||r.z1<f.z-f.length/2-1||r.z0>f.z+f.length/2+1,`${r.name} overlaps ${f.name}`);});
